import React from 'react';
import { Sparkles, Stethoscope, ShieldAlert, Cpu, Activity, Info } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';

export const AiRiskCard = ({ aiRisk, onGenerateAi, generatingAi, onOpenReview }) => {
  const { hasPermission } = useAuth();

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-5 shadow-xl space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800/80 pb-3">
        <div className="flex items-center gap-2.5">
          <div className="p-1.5 rounded-lg bg-cyan-950/80 border border-cyan-800 text-cyan-400">
            <Cpu className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white tracking-tight">AI Risk Assessment</h3>
            <p className="text-[10px] text-slate-400">24-Hour Critical Decompensation Estimator</p>
          </div>
        </div>
        <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-slate-800 border border-slate-700 text-slate-300">
          Model v{aiRisk?.model_version || '1.0'}
        </span>
      </div>

      {aiRisk ? (
        <>
          {/* Main Risk Score & Category Banner */}
          <div className="bg-slate-950/90 p-4 rounded-xl border border-slate-800 flex items-center justify-between">
            <div>
              <div className="text-[10px] uppercase font-bold tracking-wider text-slate-400">Decompensation Probability</div>
              <div className="flex items-baseline gap-2 mt-0.5">
                <span className="text-3xl font-black font-mono text-cyan-300">
                  {aiRisk.risk_probability !== undefined && aiRisk.risk_probability !== null
                    ? `${(aiRisk.risk_probability * 100).toFixed(1)}%`
                    : `${aiRisk.risk_score}%`}
                </span>
                <span className="text-xs text-slate-400 font-mono">P(Y=1)</span>
              </div>
            </div>
            <span className={`px-3 py-1.5 rounded-xl text-xs font-black tracking-wide border shadow-sm ${
              aiRisk.risk_category === 'HIGH' || aiRisk.risk_category === 'CRITICAL'
                ? 'bg-rose-950/90 text-rose-300 border-rose-700 shadow-rose-950/50'
                : aiRisk.risk_category === 'MODERATE'
                ? 'bg-amber-950/90 text-amber-300 border-amber-700 shadow-amber-950/50'
                : 'bg-emerald-950/90 text-emerald-300 border-emerald-700 shadow-emerald-950/50'
            }`}>
              {aiRisk.risk_category} RISK
            </span>
          </div>

          {/* Key Clinical Biomarkers & Predicted ESI Grid */}
          <div className="grid grid-cols-3 gap-2 text-xs font-mono">
            <div className="bg-slate-950/60 p-2.5 rounded-xl border border-slate-800 text-center">
              <div className="text-slate-400 text-[10px] uppercase">Predicted ESI</div>
              <div className="font-bold text-sm text-cyan-300 mt-0.5">Level {aiRisk.predicted_triage_level || '2'}</div>
            </div>
            <div className="bg-slate-950/60 p-2.5 rounded-xl border border-slate-800 text-center">
              <div className="text-slate-400 text-[10px] uppercase">Shock Index</div>
              <div className="font-bold text-sm text-indigo-300 mt-0.5">{aiRisk.shock_index || '—'}</div>
            </div>
            <div className="bg-slate-950/60 p-2.5 rounded-xl border border-slate-800 text-center">
              <div className="text-slate-400 text-[10px] uppercase">qSOFA Score</div>
              <div className="font-bold text-sm text-amber-300 mt-0.5">{aiRisk.qsofa ?? '—'} pts</div>
            </div>
          </div>

          {/* Clinical Decision Support Notice */}
          <div className="p-3 rounded-xl bg-slate-950/90 border border-slate-800/80 text-[11px] text-slate-300 space-y-1">
            <div className="text-amber-400 font-bold flex items-center gap-1.5 text-xs">
              <Info className="w-3.5 h-3.5 text-amber-400 shrink-0" />
              <span>Advisory Decision Support Only</span>
            </div>
            <p className="text-slate-400 text-[10px] leading-relaxed">
              Predictions are statistical risk estimates generated by ML Model v{aiRisk?.model_version || '1.0'} from intake vital signs. They do not constitute a diagnostic determination or replace clinical judgment.
            </p>
          </div>
        </>
      ) : (
        <div className="text-center py-6 space-y-3 bg-slate-950/40 rounded-xl border border-dashed border-slate-800 p-4">
          <Activity className="w-8 h-8 text-slate-600 mx-auto animate-pulse" />
          <p className="text-xs text-slate-400">No AI risk assessment has been generated yet for this encounter.</p>
          <button
            onClick={onGenerateAi}
            disabled={generatingAi}
            className="px-4 py-2 rounded-xl bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-bold shadow-md shadow-cyan-900/30 transition-all disabled:opacity-50 inline-flex items-center gap-1.5"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>{generatingAi ? 'Evaluating ML Model v1.0...' : 'Generate AI Risk Assessment'}</span>
          </button>
        </div>
      )}

      {/* Physician Action Link */}
      {onOpenReview && hasPermission('clinical_decision:create') && (
        <button
          onClick={onOpenReview}
          className="w-full py-2.5 px-3 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-bold text-xs shadow-md shadow-indigo-950/40 transition-colors flex items-center justify-center gap-1.5"
        >
          <Stethoscope className="w-4 h-4" />
          <span>Open Physician Review Console</span>
        </button>
      )}
    </div>
  );
};
